let
    Source = Excel.Workbook(File.Contents("C:\Users\Balu\Desktop\POWER BI NOTES\EmployeeData.xlsx"), null, true),
    EmployeeData1_Sheet = Source{[Item="EmployeeData1",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(EmployeeData1_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"EmployeeID", Int64.Type}, {"NationalIDNumber", Int64.Type}, {"ContactID", Int64.Type}, {"LoginID", type text}, {"ManagerID", Int64.Type}, {"Title", type text}, {"BirthDate", type datetime}, {"MaritalStatus", type text}, {"Gender", type text}, {"HireDate", type datetime}, {"Dept", type text}, {"Salary", Int64.Type}, {"Job Grade", type text}, {"CurrentFlag", Int64.Type}, {"rowguid", type text}}),
    #"Removed National ID,Contat ID" = Table.RemoveColumns(#"Changed Type",{"NationalIDNumber", "ContactID"}),
    #"Renamed Title to Full Name" = Table.RenameColumns(#"Removed National ID,Contat ID",{{"Title", "Full Name"}}),
    #"Splitted Full Name" = Table.SplitColumn(#"Renamed Title to Full Name", "Full Name", Splitter.SplitTextByEachDelimiter({" "}, QuoteStyle.Csv, false), {"Full Name.1", "Full Name.2"}),
    #"Changed Full Name to text" = Table.TransformColumnTypes(#"Splitted Full Name",{{"Full Name.1", type text}, {"Full Name.2", type text}}),
    #"Renamed as First Name,Last Name" = Table.RenameColumns(#"Changed Full Name to text",{{"Full Name.1", "First Name"}, {"Full Name.2", "Last Name"}}),
    #"Changed Birthdate type to Date" = Table.TransformColumnTypes(#"Renamed as First Name,Last Name",{{"BirthDate", type date}}),
    #"Replaced M as Married" = Table.ReplaceValue(#"Changed Birthdate type to Date","M","Married",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Replaced S as Single" = Table.ReplaceValue(#"Replaced M as Married","S","Single",Replacer.ReplaceText,{"MaritalStatus"}),
    #"Removed LoginID,ManagerID" = Table.RemoveColumns(#"Replaced S as Single",{"LoginID", "ManagerID"}),
    #"Replaced M to Male" = Table.ReplaceValue(#"Removed LoginID,ManagerID","M","Male",Replacer.ReplaceText,{"Gender"}),
    #"Replaced F to Female" = Table.ReplaceValue(#"Replaced M to Male","F","Female",Replacer.ReplaceText,{"Gender"}),
    #"Changed HiredDate type to Date" = Table.TransformColumnTypes(#"Replaced F to Female",{{"HireDate", type date}}),
    #"Removed CurrentFlag,rowguid" = Table.RemoveColumns(#"Changed HiredDate type to Date",{"CurrentFlag", "rowguid"})
in
    #"Removed CurrentFlag,rowguid"